ARG POSTGRES_IMAGE=postgres:16.10-bookworm
FROM ${POSTGRES_IMAGE}

RUN apt-get update \
  && apt-get install -y --no-install-recommends awscli openssl ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY postgres/archive-wal.sh /usr/local/bin/archive-wal.sh
COPY postgres/postgres-entrypoint.sh /usr/local/bin/rosm-postgres-entrypoint.sh
RUN chmod 0555 /usr/local/bin/archive-wal.sh /usr/local/bin/rosm-postgres-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/rosm-postgres-entrypoint.sh"]
