export const API_BASE = import.meta.env.VITE_API_BASE || 'http://localhost:8080';
export const HCAPTCHA_SITE_KEY = import.meta.env.VITE_HCAPTCHA_SITE_KEY || '';

export const SECURITY_FIELDS = [
  ['email_code_max_attempts', '验证码最大错误次数'],
  ['register_code_cooldown_seconds', '注册发码冷却(秒)'],
  ['login_code_cooldown_seconds', '验证码登录发码冷却(秒)'],
  ['admin_login_code_cooldown_seconds', '双因素发码冷却(秒)'],
  ['bind_email_code_cooldown_seconds', '绑定邮箱发码冷却(秒)'],
  ['password_reset_code_cooldown_seconds', '重置密码发码冷却(秒)'],
  ['register_code_email_limit', '注册发码邮箱次数'],
  ['register_code_ip_limit', '注册发码 IP 次数'],
  ['register_code_window_seconds', '注册发码窗口(秒)'],
  ['register_code_block_seconds', '注册发码封禁(秒)'],
  ['admin_login_code_email_limit', '登录发码邮箱次数'],
  ['admin_login_code_ip_limit', '登录发码 IP 次数'],
  ['admin_login_code_window_seconds', '登录发码窗口(秒)'],
  ['admin_login_code_block_seconds', '登录发码封禁(秒)'],
  ['login_email_limit', '登录邮箱次数'],
  ['login_ip_limit', '登录 IP 次数'],
  ['login_window_seconds', '登录窗口(秒)'],
  ['login_block_seconds', '登录封禁(秒)'],
  ['refresh_ip_limit', '刷新令牌 IP 次数'],
  ['refresh_window_seconds', '刷新令牌窗口(秒)'],
  ['refresh_block_seconds', '刷新令牌封禁(秒)'],
  ['oidc_token_ip_limit', 'OIDC Token IP 次数'],
  ['oidc_token_window_seconds', 'OIDC Token 窗口(秒)'],
  ['oidc_token_block_seconds', 'OIDC Token 封禁(秒)'],
  ['oidc_introspect_ip_limit', 'OIDC Introspect IP 次数'],
  ['oidc_introspect_window_seconds', 'OIDC Introspect 窗口(秒)'],
  ['oidc_introspect_block_seconds', 'OIDC Introspect 封禁(秒)'],
];

export const SECURITY_TOGGLE_DEFAULTS = {
  email_rate_limit_enabled: true,
  ip_rate_limit_enabled: true,
};

export const SECURITY_FIELD_DEFAULTS = {
  email_code_max_attempts: 8,
  register_code_cooldown_seconds: 45,
  login_code_cooldown_seconds: 30,
  admin_login_code_cooldown_seconds: 45,
  bind_email_code_cooldown_seconds: 45,
  password_reset_code_cooldown_seconds: 45,
  register_code_email_limit: 6,
  register_code_ip_limit: 24,
  register_code_window_seconds: 600,
  register_code_block_seconds: 600,
  admin_login_code_email_limit: 8,
  admin_login_code_ip_limit: 30,
  admin_login_code_window_seconds: 900,
  admin_login_code_block_seconds: 600,
  login_email_limit: 12,
  login_ip_limit: 36,
  login_window_seconds: 900,
  login_block_seconds: 600,
  refresh_ip_limit: 30,
  refresh_window_seconds: 300,
  refresh_block_seconds: 600,
  oidc_token_ip_limit: 30,
  oidc_token_window_seconds: 300,
  oidc_token_block_seconds: 600,
  oidc_introspect_ip_limit: 60,
  oidc_introspect_window_seconds: 300,
  oidc_introspect_block_seconds: 600,
};

export const SECURITY_FIELD_HINTS = {
  email_rate_limit_enabled: '用于需要按“单个账户”控制风险的场景，比如同一邮箱连续反复请求验证码或反复尝试登录。开启后，系统会把同一账户的请求单独累计，避免攻击者只换 IP 就绕过限制。',
  ip_rate_limit_enabled: '用于需要按“来源地址”拦截批量请求的场景，比如同一台设备或同一出口 IP 高频撞库、刷验证码。开启后，系统会把同一 IP 的请求合并统计，更适合挡住扫描和批量攻击。',
  email_code_max_attempts: '用于验证码校验阶段。用户在注册、绑定邮箱或重置密码时，如果同一封验证码连续输错达到这个次数，这封验证码就会立即作废，必须重新获取。',
  register_code_cooldown_seconds: '用于注册页里的“发送验证码”按钮。每次成功发出注册验证码后，按钮会进入这段冷却时间，在倒计时结束前不能再次发送。',
  login_code_cooldown_seconds: '用于“邮箱验证码登录”模式下的发码冷却。每次成功发送登录验证码后，只会影响这一类登录方式的重发按钮。',
  admin_login_code_cooldown_seconds: '用于“密码登录后再收邮箱验证码”的双因素场景。每次成功发送双因素验证码后，只会影响这一路径，不再和普通验证码登录、注册、重置密码共用冷却。',
  bind_email_code_cooldown_seconds: '用于绑定邮箱弹窗里的“发送验证码”按钮。每次成功发出绑定邮箱验证码后，按钮会进入这段冷却时间，在倒计时结束前不能再次发送，避免用户连续重复点击。',
  password_reset_code_cooldown_seconds: '用于重置密码弹窗里的“发送验证码”按钮。每次成功发出重置密码验证码后，按钮会进入这段冷却时间，在倒计时结束前不能再次发送。',
  register_code_email_limit: '用于注册页面发送邮箱验证码时。这个值决定“同一个邮箱”在一个统计窗口内最多能点多少次发送，适合限制有人反复给同一邮箱刷注册验证码。',
  register_code_ip_limit: '用于注册页面发送邮箱验证码时。这个值决定“同一个 IP”在一个统计窗口内最多能发多少次，适合限制机器脚本从同一网络环境批量请求注册验证码。',
  register_code_window_seconds: '用于注册发码限流的统计周期。系统会在这段时间内累计注册发码次数，并拿累计结果去和邮箱次数、IP 次数上限比较。',
  register_code_block_seconds: '用于触发注册发码限流之后的冷却时间。一旦同一邮箱或同一 IP 超过上限，在这段时间内新的注册发码请求会被直接拒绝。',
  admin_login_code_email_limit: '用于登录页发送邮箱验证码时。这个值决定“同一个邮箱”在一个统计窗口内最多能获取多少次登录验证码，适合限制对单个管理员账号的反复骚扰。',
  admin_login_code_ip_limit: '用于登录页发送邮箱验证码时。这个值决定“同一个 IP”在一个统计窗口内最多能发多少次登录验证码，适合限制来自同一来源的批量发码请求。',
  admin_login_code_window_seconds: '用于登录发码限流的统计周期。系统会在这段时间内累计登录发码次数，并据此判断是否超过邮箱或 IP 上限。',
  admin_login_code_block_seconds: '用于登录发码触发限流后的冷却时间。超过限制后，在这段时间里新的登录验证码请求会被直接拦下。',
  login_email_limit: '用于密码登录校验阶段。这个值决定“同一个账户”在一个统计窗口内最多能输错多少次密码，适合防止别人盯着某个账号持续试错。',
  login_ip_limit: '用于密码登录校验阶段。这个值决定“同一个 IP”在一个统计窗口内最多能尝试多少次登录，适合阻止同一来源批量撞库多个账号。',
  login_window_seconds: '用于密码登录限流的统计周期。系统会在这段时间内累计登录尝试次数，再根据账户或 IP 的上限判断是否需要封禁。',
  login_block_seconds: '用于密码登录触发限流后的冷却时间。一旦达到限制，在这段时间里新的密码登录请求会被直接拒绝。',
  refresh_ip_limit: '用于刷新令牌接口。这个值决定“同一个 IP”在一个统计窗口内最多能调用多少次刷新，适合防止令牌被窃取后被高频滥用。',
  refresh_window_seconds: '用于刷新令牌限流的统计周期。系统会在这段时间内累计刷新请求次数，并和刷新次数上限比较。',
  refresh_block_seconds: '用于刷新令牌接口触发限流后的冷却时间。超过次数后，在这段时间里新的刷新请求会被直接拒绝。',
  oidc_token_ip_limit: '用于 OIDC Token 端点。这个值决定“同一个 IP”在一个统计窗口内最多能请求多少次换取令牌，适合限制接入应用异常重试或恶意刷 token。',
  oidc_token_window_seconds: '用于 OIDC Token 端点限流的统计周期。系统会在这段时间内累计 token 请求次数，并据此判断是否达到上限。',
  oidc_token_block_seconds: '用于 OIDC Token 端点触发限流后的冷却时间。超过限制后，在这段时间里新的 token 请求会被直接拒绝。',
  oidc_introspect_ip_limit: '用于 OIDC Introspect 端点。这个值决定“同一个 IP”在一个统计窗口内最多能查询多少次令牌状态，适合限制接入方异常轮询或恶意探测。',
  oidc_introspect_window_seconds: '用于 OIDC Introspect 端点限流的统计周期。系统会在这段时间内累计 introspect 请求次数，并和次数上限比较。',
  oidc_introspect_block_seconds: '用于 OIDC Introspect 端点触发限流后的冷却时间。超过限制后，在这段时间里新的 introspect 请求会被直接拒绝。',
};

export const PAGE_META = {
  overview: {
    label: '指挥台',
    title: '身份系统总览',
    description: '把账号、协议接入与系统配置放到一块更轻盈的画布里。',
  },
  profile: {
    label: '账号安全',
    title: '个人资料与安全',
    description: '更新昵称、邮箱和密码，快速处理账号安全动作。',
  },
  system: {
    label: '系统配置',
    title: '安全策略与 SMTP',
    description: '验证码、限流阈值、SMTP 与注册策略都集中管理。',
  },
  templates: {
    label: '通知中心',
    title: '邮件模板工作台',
    description: '切换模板、编辑 HTML/纯文本内容，并保持发送主题一致。',
  },
  oidc: {
    label: '开放接入',
    title: 'OIDC 接入控制台',
    description: '查看 discovery 信息、客户端列表，并创建或更新客户端。',
  },
  users: {
    label: '权限视图',
    title: '用户与角色',
    description: '查看当前用户池和角色分布，确认后台权限情况。',
  },
  audits: {
    label: '审计视图',
    title: '审计与合规',
    description: '浏览最近操作记录与安全事件，帮助追踪系统变化。',
  },
};
